steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/itsm-backend', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/itsm-backend']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    'itsm-backend',
    '--image', 'gcr.io/$PROJECT_ID/itsm-backend',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars',
    'MONGODB_URI=${_MONGODB_URI},
    JWT_SECRET=${_JWT_SECRET},
    SLACK_BOT_TOKEN=${_SLACK_BOT_TOKEN},
    SLACK_SIGNING_SECRET=${_SLACK_SIGNING_SECRET},
    EMAIL_USER=${_EMAIL_USER},
    EMAIL_PASS=${_EMAIL_PASS},
    FRONTEND_URL=${_FRONTEND_URL},
    SLACK_APPROVAL_CHANNEL=${_SLACK_APPROVAL_CHANNEL},
    MONGODB_SSL_CA=${_MONGODB_SSL_CA},
    MONGODB_SSL_CERT=${_MONGODB_SSL_CERT},
    MONGODB_SSL_KEY=${_MONGODB_SSL_KEY},
    MONGODB_SSL_PASS=${_MONGODB_SSL_PASS}'
  ]

images:
- gcr.io/$PROJECT_ID/itsm-backend

substitutions:
  _MONGODB_URI: ''
  _JWT_SECRET: ''
  _SLACK_BOT_TOKEN: ''
  _SLACK_SIGNING_SECRET: ''
  _EMAIL_USER: ''
  _EMAIL_PASS: ''
  _FRONTEND_URL: ''
  _SLACK_APPROVAL_CHANNEL: ''
  _MONGODB_SSL_CA: ''
  _MONGODB_SSL_CERT: ''
  _MONGODB_SSL_KEY: ''
  _MONGODB_SSL_PASS: ''
