name: Backend Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # Build application
      - name: Build application
        run: npm run build
        working-directory: backend

      # Configure Google Cloud
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Set up environment variables
      - name: Set up environment variables
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BACKUP_DIR: ${{ secrets.BACKUP_DIR }}
          BACKUP_RETENTION_DAYS: ${{ secrets.BACKUP_RETENTION_DAYS }}
          BACKUP_INTERVAL_MINUTES: ${{ secrets.BACKUP_INTERVAL_MINUTES }}
          MAX_BACKUP_SIZE_MB: ${{ secrets.MAX_BACKUP_SIZE_MB }}
          MAX_BACKUP_FILES: ${{ secrets.MAX_BACKUP_FILES }}
          FIREBASE_PROJECT_ID: itsm-project-bb01a
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "Environment variables set successfully"

      # Push to Google Container Registry
      - name: Push to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend:${{ github.sha }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy itsm-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}" \
            --set-env-vars="JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars="BACKUP_DIR=${{ secrets.BACKUP_DIR }}" \
            --set-env-vars="BACKUP_RETENTION_DAYS=${{ secrets.BACKUP_RETENTION_DAYS }}" \
            --set-env-vars="BACKUP_INTERVAL_MINUTES=${{ secrets.BACKUP_INTERVAL_MINUTES }}" \
            --set-env-vars="MAX_BACKUP_SIZE_MB=${{ secrets.MAX_BACKUP_SIZE_MB }}" \
            --set-env-vars="MAX_BACKUP_FILES=${{ secrets.MAX_BACKUP_FILES }}" \
            --set-env-vars="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" \
            --set-env-vars="FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" \
            --set-env-vars="GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --set-env-vars="GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}"

      # Cache build
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            backend/node_modules
            backend/.next
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-
