name: Backend Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: backend

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend:${{ github.sha }} .
        working-directory: backend

      # Configure Google Cloud
      - name: Configure Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Push to Google Container Registry
      - name: Push to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend:${{ github.sha }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy itsm-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}" \
            --set-env-vars="JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars="BACKUP_DIR=${{ secrets.BACKUP_DIR }}" \
            --set-env-vars="BACKUP_RETENTION_DAYS=${{ secrets.BACKUP_RETENTION_DAYS }}" \
            --set-env-vars="BACKUP_INTERVAL_MINUTES=${{ secrets.BACKUP_INTERVAL_MINUTES }}" \
            --set-env-vars="MAX_BACKUP_SIZE_MB=${{ secrets.MAX_BACKUP_SIZE_MB }}" \
            --set-env-vars="MAX_BACKUP_FILES=${{ secrets.MAX_BACKUP_FILES }}" \
            --set-env-vars="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" \
            --set-env-vars="FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" \
            --set-env-vars="GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" \
            --set-env-vars="GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}"

      # Cache build
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            backend/node_modules
            backend/.next
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-
