name: SSL Certificate Management

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  renew-certificates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SSL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y certbot python3-certbot-dns-google

      - name: Configure Google Cloud DNS
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Renew SSL certificates
        run: |
          certbot certonly \
            --dns-google \
            --dns-google-credentials "${{ secrets.GCP_SA_KEY }}" \
            --domain "${{ secrets.DOMAIN }}" \
            --domain "*.${{ secrets.DOMAIN }}" \
            --non-interactive \
            --agree-tos \
            --email "${{ secrets.ADMIN_EMAIL }}"

      - name: Upload certificates to Firebase
        run: |
          firebase storage:upload \
            --project "${{ secrets.FIREBASE_PROJECT_ID }}" \
            --path "/ssl-certificates/${{ secrets.DOMAIN }}" \
            "/etc/letsencrypt/live/${{ secrets.DOMAIN }}/*"

      - name: Update environment variables
        run: |
          echo "MONGODB_SSL_CA=$(cat /etc/letsencrypt/live/${{ secrets.DOMAIN }}/fullchain.pem)" >> $GITHUB_ENV
          echo "MONGODB_SSL_CERT=$(cat /etc/letsencrypt/live/${{ secrets.DOMAIN }}/cert.pem)" >> $GITHUB_ENV
          echo "MONGODB_SSL_KEY=$(cat /etc/letsencrypt/live/${{ secrets.DOMAIN }}/privkey.pem)" >> $GITHUB_ENV

      - name: Deploy updated certificates
        run: |
          gcloud run deploy itsm-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/itsm-backend \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "MONGODB_SSL_CA=${{ env.MONGODB_SSL_CA }},
              MONGODB_SSL_CERT=${{ env.MONGODB_SSL_CERT }},
              MONGODB_SSL_KEY=${{ env.MONGODB_SSL_KEY }}"

      - name: Verify SSL
        run: |
          curl -I -k https://${{ secrets.DOMAIN }} | grep -i "HTTP/2 200"
